{% set name = "coincurve" %}
{% set version = "13.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9985627dc0c81fe98c3d2e97412801e9726d6110249317a2775cf365f0ba0df5

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - asn1crypto
    - cffi >=1.3.0
    - pip
    - python
    - requests
  run:
    - asn1crypto
    - cffi >=1.3.0
    - python

test:
  imports:
    - coincurve

about:
  home: "https://github.com/ofek/coincurve"
  license: MIT License or Apache Software
  license_family: MIT
  license_file:
  summary: "Cross-platform Python CFFI bindings for libsecp256k1"
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - OverlordQ
