{% set name = "coincurve" %}
{% set version = "13.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9985627dc0c81fe98c3d2e97412801e9726d6110249317a2775cf365f0ba0df5

build:
  number: 0
  skip: True  # [py<35]
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
    - automake
    - pkg-config
    - libtool
    - libffi
    - gmp
  host:
    - python
    - pip
  run:
    - python

test:
  requires:
    - pytest
  commands:
    - py.test --pyargs coincurve 

about:
  home: https://github.com/ofek/coincurve
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Cross-platform Python CFFI bindings for libsecp256k1'

extra:
  recipe-maintainers:
   - OverlordQ
