{% set name = "libsecp256k1" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
    git_url: https://github.com/bitcoin-core/secp256k1.git
    git_depth: 1

build:
  skip: true  # [win]
  number: 0

requirements:
    build:
        - autoconf
        - automake
        - libtool
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - pkg-config --cflags --libs libsecp256k1  # [unix]

about:
  home: https://github.com/bitcoin-core/secp256k1
  license: MIT
  license_file: COPYING
  summary: 'Optimized C library for EC operations on curve secp256k1'


extra:
  recipe-maintainers:
    - OverlordQ
